### ISSUE TITLE
UIActionSheet Orientation on Site Delete Orientation

### ISSUE THREAD

**Issue by dennismajor1** [tkadauke/TinyMon#1]
A small issue - on iPad version of app when deleting a "site object" the UIActionSheet delete cancel prompt does not orientate to landscape mode along with the rest of the view.

**Comment by tkadauke** [comment]
Sorry for getting back to you so late. I didn't see this issue until now :-(

What do you mean by iPad version? Is that when you run the app on the iPad / iPad simulator? There is no native support for the iPad yet.
