### ISSUE TITLE
my issue? you're hogging all the cool!

### ISSUE THREAD

**Issue by colinta** [tkadauke/TinyMon#2]
Somehow the `CAGradientLayer` class has never caught my eye - I dig the `teacup_gradient_handler.rb` addition!  I'm just sad it hasn't resulted in a pull request...

I would like it if changes to the `gradient:` could make changes to the same layer... but that would involve either searching for a `CAGradientLayer` in the `layer.sublayers` or holding onto a reference (`gradient = self.instance_variable_get('@sweettea_gradient_layer')...self.instance_variable_set('@sweettea_gradient_layer', gradient)`)

https://github.com/colinta/sweettea/pull/new/master!

**Comment by tkadauke** [comment]
Why would this go into sweattea and not into Teacup? I am not sure I want to use Sugarcube in TinyMon, but could obviously profit from the extension. That might be the case for many other people.

That being said, I'd be happy to add the handler to Teacup.

**Comment by colinta** [comment]
Hmm... I wanted to keep the teacup handlers as trim as possible, but I see your point, there's nothing here sugarcube-specific.

I think this could have a good home in teacup - so yeah, works for me!

**Comment by tkadauke** [comment]
TinyMon now uses the latest version of Teacup including the gradient handler.
