### ISSUE TITLE
searching in sites does not reuse cells

### ISSUE THREAD

**Issue by soma** [tkadauke/TinyMon#3]
Because of the delegation, the tableview that gets the cells are not in self.table but in searchDisplayController.searchResultsTableView ... something like this fixes it.

 90   def fresh_cell  
 91     table_view_for_context.dequeueReusableCellWithIdentifier('Cell') ||
 92       YourTableViewCell.alloc.initWithStyle(UITableViewCellStyleSubtitle, reuseIdentifier:'Cell').tap do |cell|
 93         cell.accessoryType = UITableViewCellAccessoryDisclosureIndicator
 94       end  
 95   end
 96  
 97   def table_view_for_context
 98     if self.searchDisplayController.isActive
 99       searchDisplayController.searchResultsTableView
100     else
101       self.tableView  
102     end  
103   end

**Comment by soma** [comment]
ops please excuse my bad pasting skills... 

anyways I am using your app as inspiration for an app I am currently tinkering with. So thanks a lot :)

**Comment by tkadauke** [comment]
Thanks for reporting that! My newest commit fixes the issue.
